from script import load_image, pygame
fon_image = load_image('image/fon')
player_1_attack_image = load_image('image/player 1/attack')
player_1_idle_image = load_image('image/player 1/idle')
player_11_attack_image = load_image('image/player 1/attack 2')
player_1_run_image = load_image('image/player 1/run')
player_2_attack_image = load_image('image/player 2/attack')
player_2_idle_image = load_image('image/player 2/idle')
player_2_run_image = load_image('image/player 2/run')
button_image = pygame.image.load('image/button/button (1).png').convert_alpha()
aizen_attack_image = load_image('image/aizen/attack')
aizen_idle_image = load_image('image/aizen/idle')
aizen_run_image = load_image('image/aizen/run')
aizen_attack2_image = load_image('image/aizen/attack 2')

